/**
  ***********************************************************
  @file   /st/spec/STM32G07x_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once




namespace mpp::io
{
  inline namespace STM32G07x_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      F = GPIOF_BASE,
    };

    template< typename IO >
    constexpr bool IsValidIo()
    {
      switch(IO::kPort)
      { 
        case Port::A: return IO::kPin < 16u;
        case Port::B: return IO::kPin < 16u;
        case Port::C: return IO::kPin < 16u;
        case Port::D: return (IO::kPin < 9u)&&(IO::kPin != 7u); 
        case Port::F: return IO::kPin < 3u;

        default: return false;
      }
    }


    

    struct PA0  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 0u;
      enum { COMP1_OUT = 7ul,  LPTIM1_OUT = 5ul,  SPI2_SCK = 0ul,  TIM2_CH1 = 2ul,  TIM2_ETR = 2ul,  UCPD2_FRSTX = 6ul,  USART2_CTS = 1ul,  USART2_NSS = 1ul,  USART4_TX = 4ul, }; 
    };

    struct PA1  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 1u;
      enum { EVENTOUT = 7ul,  I2C1_SMBA = 6ul,  I2S1_CK = 0ul,  SPI1_SCK = 0ul,  TIM15_CH1N = 5ul,  TIM2_CH2 = 2ul,  UCPD1_TXGND = 3ul,  USART2_CK = 1ul,  USART2_DE = 1ul,  USART2_RTS = 1ul,  USART4_RX = 4ul, }; 
    };

    struct PA10 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 10u;
      enum { EVENTOUT = 7ul,  I2C1_SDA = 6ul,  SPI2_MOSI = 0ul,  TIM17_BK = 5ul,  TIM1_CH3 = 2ul,  UCPD2_TXGND = 3ul,  USART1_RX = 1ul, }; 
    };


    struct PA11 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 11u;
      enum { COMP1_OUT = 7ul,  I2C2_SCL = 6ul,  I2S1_MCK = 0ul,  SPI1_MISO = 0ul,  TIM1_BK2 = 5ul,  TIM1_CH4 = 2ul,  USART1_CTS = 1ul,  USART1_NSS = 1ul, }; 
    };

    struct PA12 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 12u;
      enum { COMP2_OUT = 7ul,  I2C2_SDA = 6ul,  I2S1_SD = 0ul,  I2S_CKIN = 5ul,  SPI1_MOSI = 0ul,  TIM1_ETR = 2ul,  USART1_CK = 1ul,  USART1_DE = 1ul,  USART1_RTS = 1ul, }; 
    };

    struct PA13 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 13u;
      enum { EVENTOUT = 7ul,  IR_OUT = 1ul,  SYS_SWDIO = 0ul, }; 
    };

    struct PA14 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 14u;
      enum { EVENTOUT = 7ul,  SYS_SWCLK = 0ul,  USART2_TX = 1ul, }; 
    };

    struct PA15 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 15u;
      enum { EVENTOUT = 7ul,  I2S1_WS = 0ul,  SPI1_NSS = 0ul,  TIM2_CH1 = 2ul,  TIM2_ETR = 2ul,  USART2_RX = 1ul,  USART3_CK = 5ul,  USART3_DE = 5ul,  USART3_RTS = 5ul,  USART4_CK = 4ul,  USART4_DE = 4ul,  USART4_RTS = 4ul, }; 
    };

    struct PA2  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 2u;
      enum { COMP2_OUT = 7ul,  I2S1_SD = 0ul,  LPUART1_TX = 6ul,  SPI1_MOSI = 0ul,  TIM15_CH1 = 5ul,  TIM2_CH3 = 2ul,  UCPD1_FRSTX = 4ul,  USART2_TX = 1ul, }; 
    };

    struct PA3  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 3u;
      enum { EVENTOUT = 7ul,  LPUART1_RX = 6ul,  SPI2_MISO = 0ul,  TIM15_CH2 = 5ul,  TIM2_CH4 = 2ul,  UCPD2_FRSTX = 4ul,  UCPD2_TXGND = 3ul,  USART2_RX = 1ul, }; 
    };

    struct PA4  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 4u;
      enum { EVENTOUT = 7ul,  I2S1_WS = 0ul,  LPTIM2_OUT = 5ul,  SPI1_NSS = 0ul,  SPI2_MOSI = 1ul,  TIM14_CH1 = 4ul,  UCPD2_FRSTX = 6ul, }; 
    };

    struct PA5  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 5u;
      enum { HDMI_CEC = 1ul,  EVENTOUT = 7ul,  I2S1_CK = 0ul,  LPTIM2_ETR = 5ul,  SPI1_SCK = 0ul,  TIM2_CH1 = 2ul,  TIM2_ETR = 2ul,  UCPD1_FRSTX = 6ul,  UCPD1_TXDATA = 3ul,  USART3_TX = 4ul, }; 
    };

    struct PA6  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 6u;
      enum { COMP1_OUT = 7ul,  I2S1_MCK = 0ul,  LPUART1_CTS = 6ul,  SPI1_MISO = 0ul,  TIM16_CH1 = 5ul,  TIM1_BK = 2ul,  TIM3_CH1 = 1ul,  UCPD1_TXDATA = 3ul,  USART3_CTS = 4ul,  USART3_NSS = 4ul, }; 
    };

    struct PA7  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 7u;
      enum { COMP2_OUT = 7ul,  I2S1_SD = 0ul,  SPI1_MOSI = 0ul,  TIM14_CH1 = 4ul,  TIM17_CH1 = 5ul,  TIM1_CH1N = 2ul,  TIM3_CH2 = 1ul,  UCPD1_FRSTX = 6ul,  UCPD2_TXDATA = 3ul, }; 
    };

    struct PA8  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 8u;
      enum { EVENTOUT = 7ul,  LPTIM2_OUT = 5ul,  RCC_MCO = 0ul,  SPI2_NSS = 1ul,  TIM1_CH1 = 2ul,  UCPD2_TXDATA = 3ul, }; 
    };

    struct PA9  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 9u;
      enum { EVENTOUT = 7ul,  I2C1_SCL = 6ul,  RCC_MCO = 0ul,  SPI2_MISO = 4ul,  TIM15_BK = 5ul,  TIM1_CH2 = 2ul,  UCPD1_TXGND = 3ul,  USART1_TX = 1ul, }; 
    };


    struct PB0  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 0u;
      enum { COMP1_OUT = 7ul,  I2S1_WS = 0ul,  LPTIM1_OUT = 5ul,  SPI1_NSS = 0ul,  TIM1_CH2N = 2ul,  TIM3_CH3 = 1ul,  UCPD1_FRSTX = 6ul,  USART3_RX = 4ul, }; 
    };

    struct PB1  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 1u;
      enum { EVENTOUT = 7ul,  LPTIM2_IN1 = 5ul,  LPUART1_DE = 6ul,  LPUART1_RTS = 6ul,  TIM14_CH1 = 0ul,  TIM1_CH3N = 2ul,  TIM3_CH4 = 1ul,  USART3_CK = 4ul,  USART3_DE = 4ul,  USART3_RTS = 4ul, }; 
    };

    struct PB10 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 10u;
      enum { HDMI_CEC = 0ul,  COMP1_OUT = 7ul,  I2C2_SCL = 6ul,  LPUART1_RX = 1ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 2ul,  UCPD1_TXGND = 3ul,  USART3_TX = 4ul, }; 
    };

    struct PB11 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 11u;
      enum { COMP2_OUT = 7ul,  I2C2_SDA = 6ul,  LPUART1_TX = 1ul,  SPI2_MOSI = 0ul,  TIM2_CH4 = 2ul,  UCPD1_TXGND = 3ul,  USART3_RX = 4ul, }; 
    };

    struct PB12 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 12u;
      enum { EVENTOUT = 7ul,  LPUART1_DE = 1ul,  LPUART1_RTS = 1ul,  SPI2_NSS = 0ul,  TIM15_BK = 5ul,  TIM1_BK = 2ul,  UCPD2_FRSTX = 6ul, }; 
    };

    struct PB13 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 13u;
      enum { EVENTOUT = 7ul,  I2C2_SCL = 6ul,  LPUART1_CTS = 1ul,  SPI2_SCK = 0ul,  TIM15_CH1N = 5ul,  TIM1_CH1N = 2ul,  UCPD2_TXGND = 3ul,  USART3_CTS = 4ul,  USART3_NSS = 4ul, }; 
    };

    struct PB14 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 14u;
      enum { EVENTOUT = 7ul,  I2C2_SDA = 6ul,  SPI2_MISO = 0ul,  TIM15_CH1 = 5ul,  TIM1_CH2N = 2ul,  UCPD1_FRSTX = 1ul,  UCPD2_TXGND = 3ul,  USART3_CK = 4ul,  USART3_DE = 4ul,  USART3_RTS = 4ul, }; 
    };

    struct PB15 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 15u;
      enum { EVENTOUT = 7ul,  SPI2_MOSI = 0ul,  TIM15_CH1N = 4ul,  TIM15_CH2 = 5ul,  TIM1_CH3N = 2ul, }; 
    };

    struct PB2  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 2u;
      enum { EVENTOUT = 7ul,  LPTIM1_OUT = 5ul,  SPI2_MISO = 1ul,  UCPD1_TXGND = 3ul,  USART3_TX = 4ul, }; 
    };

    struct PB3  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 3u;
      enum { EVENTOUT = 7ul,  I2S1_CK = 0ul,  SPI1_SCK = 0ul,  TIM1_CH2 = 1ul,  TIM2_CH2 = 2ul,  USART1_CK = 4ul,  USART1_DE = 4ul,  USART1_RTS = 4ul, }; 
    };

    struct PB4  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 4u;
      enum { EVENTOUT = 7ul,  I2S1_MCK = 0ul,  SPI1_MISO = 0ul,  TIM17_BK = 5ul,  TIM3_CH1 = 1ul,  UCPD2_TXGND = 3ul,  USART1_CTS = 4ul,  USART1_NSS = 4ul, }; 
    };

    struct PB5  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 5u;
      enum { COMP2_OUT = 7ul,  I2C1_SMBA = 6ul,  I2S1_SD = 0ul,  LPTIM1_IN1 = 5ul,  SPI1_MOSI = 0ul,  TIM16_BK = 2ul,  TIM3_CH2 = 1ul, }; 
    };

    struct PB6  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 6u;
      enum { EVENTOUT = 7ul,  I2C1_SCL = 6ul,  LPTIM1_ETR = 5ul,  SPI2_MISO = 4ul,  TIM16_CH1N = 2ul,  TIM1_CH3 = 1ul,  UCPD1_TXGND = 3ul,  USART1_TX = 0ul, }; 
    };

    struct PB7  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 7u;
      enum { EVENTOUT = 7ul,  I2C1_SDA = 6ul,  LPTIM1_IN2 = 5ul,  SPI2_MOSI = 1ul,  TIM17_CH1N = 2ul,  USART1_RX = 0ul,  USART4_CTS = 4ul,  USART4_NSS = 4ul, }; 
    };

    struct PB8  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 8u;
      enum { HDMI_CEC = 0ul,  EVENTOUT = 7ul,  I2C1_SCL = 6ul,  SPI2_SCK = 1ul,  TIM15_BK = 5ul,  TIM16_CH1 = 2ul,  UCPD1_TXGND = 3ul,  USART3_TX = 4ul, }; 
    };

    struct PB9  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 9u;
      enum { EVENTOUT = 7ul,  I2C1_SDA = 6ul,  IR_OUT = 0ul,  SPI2_NSS = 5ul,  TIM17_CH1 = 2ul,  UCPD2_FRSTX = 1ul,  UCPD2_TXGND = 3ul,  USART3_RX = 4ul, }; 
    };

    struct PC0  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 0u;
      enum { LPTIM1_IN1 = 0ul,  LPTIM2_IN1 = 2ul,  LPUART1_RX = 1ul,  UCPD1_TXGND = 3ul, }; 
    };

    struct PC1  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 1u;
      enum { LPTIM1_OUT = 0ul,  LPUART1_TX = 1ul,  TIM15_CH1 = 2ul,  UCPD1_TXGND = 3ul, }; 
    };

    struct PC10 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 10u;
      enum { TIM1_CH3 = 2ul,  UCPD2_TXDATA = 3ul,  USART3_TX = 0ul,  USART4_TX = 1ul, }; 
    };

    struct PC11 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 11u;
      enum { TIM1_CH4 = 2ul,  UCPD2_TXDATA = 3ul,  USART3_RX = 0ul,  USART4_RX = 1ul, }; 
    };

    struct PC12 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 12u;
      enum { LPTIM1_IN1 = 0ul,  TIM14_CH1 = 2ul,  UCPD1_FRSTX = 1ul, }; 
    };

    struct PC13 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 13u;
      enum { TIM1_BK = 2ul, }; 
    };

    struct PC14 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 14u;
      enum { TIM1_BK2 = 2ul, }; 
    };

    struct PC15 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 15u;
      enum { RCC_OSC32_EN = 0ul,  RCC_OSC_EN = 1ul,  TIM15_BK = 2ul, }; 
    };

    struct PC2  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 2u;
      enum { LPTIM1_IN2 = 0ul,  SPI2_MISO = 1ul,  TIM15_CH2 = 2ul,  UCPD2_TXGND = 3ul, }; 
    };

    struct PC3  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 3u;
      enum { LPTIM1_ETR = 0ul,  LPTIM2_ETR = 2ul,  SPI2_MOSI = 1ul,  UCPD2_TXGND = 3ul, }; 
    };

    struct PC4  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 4u;
      enum { TIM2_CH1 = 2ul,  TIM2_ETR = 2ul,  USART1_TX = 1ul,  USART3_TX = 0ul, }; 
    };

    struct PC5  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 5u;
      enum { TIM2_CH2 = 2ul,  UCPD2_TXGND = 3ul,  USART1_RX = 1ul,  USART3_RX = 0ul, }; 
    };

    struct PC6  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 6u;
      enum { TIM2_CH3 = 2ul,  TIM3_CH1 = 1ul,  UCPD1_FRSTX = 0ul,  UCPD1_TXDATA = 3ul, }; 
    };

    struct PC7  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 7u;
      enum { TIM2_CH4 = 2ul,  TIM3_CH2 = 1ul,  UCPD2_FRSTX = 0ul,  UCPD2_TXDATA = 3ul, }; 
    };

    struct PC8  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 8u;
      enum { TIM1_CH1 = 2ul,  TIM3_CH3 = 1ul,  UCPD1_TXDATA = 3ul,  UCPD2_FRSTX = 0ul, }; 
    };

    struct PC9  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 9u;
      enum { I2S_CKIN = 0ul,  TIM1_CH2 = 2ul,  TIM3_CH4 = 1ul,  UCPD1_TXDATA = 3ul, }; 
    };

    struct PD0  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 0u;
      enum { EVENTOUT = 0ul,  SPI2_NSS = 1ul,  TIM16_CH1 = 2ul,  UCPD1_TXDATA = 3ul, }; 
    };

    struct PD1  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 1u;
      enum { EVENTOUT = 0ul,  SPI2_SCK = 1ul,  TIM17_CH1 = 2ul,  UCPD1_TXDATA = 3ul, }; 
    };

    struct PD2  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 2u;
      enum { TIM1_CH1N = 2ul,  TIM3_ETR = 1ul,  UCPD2_TXDATA = 3ul,  USART3_CK = 0ul,  USART3_DE = 0ul,  USART3_RTS = 0ul, }; 
    };

    struct PD3  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 3u;
      enum { SPI2_MISO = 1ul,  TIM1_CH2N = 2ul,  UCPD2_TXDATA = 3ul,  USART2_CTS = 0ul,  USART2_NSS = 0ul, }; 
    };

    struct PD4  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 4u;
      enum { SPI2_MOSI = 1ul,  TIM1_CH3N = 2ul,  USART2_CK = 0ul,  USART2_DE = 0ul,  USART2_RTS = 0ul, }; 
    };

    struct PD5  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2S1_MCK = 1ul,  SPI1_MISO = 1ul,  TIM1_BK = 2ul,  USART2_TX = 0ul, }; 
    };

    struct PD6  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2S1_SD = 1ul,  LPTIM2_OUT = 2ul,  SPI1_MOSI = 1ul,  USART2_RX = 0ul, }; 
    };

    struct PD8  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 8u;
      enum { I2S1_CK = 1ul,  LPTIM1_OUT = 2ul,  SPI1_SCK = 1ul,  UCPD1_TXDATA = 3ul,  USART3_TX = 0ul, }; 
    };

    struct PD9  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 9u;
      enum { I2S1_WS = 1ul,  SPI1_NSS = 1ul,  TIM1_BK2 = 2ul,  UCPD2_TXDATA = 3ul,  USART3_RX = 0ul, }; 
    };

    struct PF0  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 0u;
      enum { TIM14_CH1 = 2ul, }; 
    };

    struct PF1  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 1u;
      enum { RCC_OSC_EN = 0ul,  TIM15_CH1N = 2ul, }; 
    };

    struct PF2  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 2u;
      enum { RCC_MCO = 0ul, }; 
    };
    
  } // inline namespace 
} // namespace mpp::io 
 
