/**
  ***********************************************************
  @file   /st/spec/STM32F411_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once


namespace mpp::io
{
  inline namespace STM32F411_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      E = GPIOE_BASE,
      H = GPIOH_BASE,
    };

    template< typename IO >
    constexpr bool IsValidIo()
    {
      switch(IO::kPort)
      { 
        case Port::A: return IO::kPin < 16u;
        case Port::B: return IO::kPin < 16u;
        case Port::C: return IO::kPin < 16u;
        case Port::D: return IO::kPin < 16u;
        case Port::E: return IO::kPin < 16u;
        case Port::H: return IO::kPin < 2u;

        default: return false;
      }
    }


    

    struct PA0  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 0u;
      enum { TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM5_CH1 = 2ul,  USART2_CTS = 7ul, }; 
    };

    struct PA1  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 1u;
      enum { I2S4_SD = 5ul,  SPI4_MOSI = 5ul,  TIM2_CH2 = 1ul,  TIM5_CH2 = 2ul,  USART2_RTS = 7ul, }; 
    };

    struct PA10 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 10u;
      enum { I2S5_SD = 6ul,  SPI5_MOSI = 6ul,  TIM1_CH3 = 1ul,  USART1_RX = 7ul,  USB_OTG_FS_ID = 10ul, }; 
    };

    struct PA11 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 11u;
      enum { SPI4_MISO = 6ul,  TIM1_CH4 = 1ul,  USART1_CTS = 7ul,  USART6_TX = 8ul,  USB_OTG_FS_DM = 10ul, }; 
    };

    struct PA12 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 12u;
      enum { SPI5_MISO = 6ul,  TIM1_ETR = 1ul,  USART1_RTS = 7ul,  USART6_RX = 8ul,  USB_OTG_FS_DP = 10ul, }; 
    };

    struct PA13 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 13u;
      enum { SYS_JTMS_SWDIO = 0ul, }; 
    };

    struct PA14 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 14u;
      enum { SYS_JTCK_SWCLK = 0ul, }; 
    };

    struct PA15 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 15u;
      enum { I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SYS_JTDI = 0ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  USART1_TX = 7ul, }; 
    };

    struct PA2  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 2u;
      enum { I2S_CKIN = 5ul,  TIM2_CH3 = 1ul,  TIM5_CH3 = 2ul,  TIM9_CH1 = 3ul,  USART2_TX = 7ul, }; 
    };

    struct PA3  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 3u;
      enum { I2S2_MCK = 5ul,  TIM2_CH4 = 1ul,  TIM5_CH4 = 2ul,  TIM9_CH2 = 3ul,  USART2_RX = 7ul, }; 
    };

    struct PA4  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 4u;
      enum { I2S1_WS = 5ul,  I2S3_WS = 6ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  USART2_CK = 7ul, }; 
    };

    struct PA5  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2S1_CK = 5ul,  SPI1_SCK = 5ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul, }; 
    };

    struct PA6  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2S2_MCK = 6ul,  SDIO_CMD = 12ul,  SPI1_MISO = 5ul,  TIM1_BKIN = 1ul,  TIM3_CH1 = 2ul, }; 
    };

    struct PA7  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 7u;
      enum { I2S1_SD = 5ul,  SPI1_MOSI = 5ul,  TIM1_CH1N = 1ul,  TIM3_CH2 = 2ul, }; 
    };

    struct PA8  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 8u;
      enum { I2C3_SCL = 4ul,  RCC_MCO_1 = 0ul,  SDIO_D1 = 12ul,  TIM1_CH1 = 1ul,  USART1_CK = 7ul,  USB_OTG_FS_SOF = 10ul, }; 
    };

    struct PA9  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 9u;
      enum { I2C3_SMBA = 4ul,  SDIO_D2 = 12ul,  TIM1_CH2 = 1ul,  USART1_TX = 7ul,  USB_OTG_FS_VBUS = 10ul, }; 
    };

    struct PB0  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 0u;
      enum { I2S5_CK = 6ul,  SPI5_SCK = 6ul,  TIM1_CH2N = 1ul,  TIM3_CH3 = 2ul, }; 
    };

    struct PB1  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 1u;
      enum { I2S5_WS = 6ul,  SPI5_NSS = 6ul,  TIM1_CH3N = 1ul,  TIM3_CH4 = 2ul, }; 
    };

    struct PB10 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 10u;
      enum { I2C2_SCL = 4ul,  I2S2_CK = 5ul,  I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 1ul, }; 
    };

    struct PB11 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 11u;
      enum { I2C2_SDA = 4ul,  I2S_CKIN = 5ul,  TIM2_CH4 = 1ul, }; 
    };

    struct PB12 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 12u;
      enum { I2C2_SMBA = 4ul,  I2S2_WS = 5ul,  I2S3_CK = 7ul,  I2S4_WS = 6ul,  SPI2_NSS = 5ul,  SPI3_SCK = 7ul,  SPI4_NSS = 6ul,  TIM1_BKIN = 1ul, }; 
    };

    struct PB13 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 13u;
      enum { I2S2_CK = 5ul,  I2S4_CK = 6ul,  SPI2_SCK = 5ul,  SPI4_SCK = 6ul,  TIM1_CH1N = 1ul, }; 
    };

    struct PB14 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 14u;
      enum { I2S2_ext_SD = 6ul,  SDIO_D6 = 12ul,  SPI2_MISO = 5ul,  TIM1_CH2N = 1ul, }; 
    };

    struct PB15 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 15u;
      enum { I2S2_SD = 5ul,  RTC_REFIN = 0ul,  SDIO_CK = 12ul,  SPI2_MOSI = 5ul,  TIM1_CH3N = 1ul, }; 
    };

    struct PB2  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 2u;
    };

    struct PB3  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 3u;
      enum { I2C2_SDA = 9ul,  I2S1_CK = 5ul,  I2S3_CK = 6ul,  SPI1_SCK = 5ul,  SPI3_SCK = 6ul,  SYS_JTDO_SWO = 0ul,  TIM2_CH2 = 1ul,  USART1_RX = 7ul, }; 
    };

    struct PB4  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 4u;
      enum { I2C3_SDA = 9ul,  I2S3_ext_SD = 7ul,  SDIO_D0 = 12ul,  SPI1_MISO = 5ul,  SPI3_MISO = 6ul,  SYS_JTRST = 0ul,  TIM3_CH1 = 2ul, }; 
    };

    struct PB5  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2C1_SMBA = 4ul,  I2S1_SD = 5ul,  I2S3_SD = 6ul,  SDIO_D3 = 12ul,  SPI1_MOSI = 5ul,  SPI3_MOSI = 6ul,  TIM3_CH2 = 2ul, }; 
    };

    struct PB6  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2C1_SCL = 4ul,  TIM4_CH1 = 2ul,  USART1_TX = 7ul, }; 
    };

    struct PB7  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 7u;
      enum { I2C1_SDA = 4ul,  SDIO_D0 = 12ul,  TIM4_CH2 = 2ul,  USART1_RX = 7ul, }; 
    };

    struct PB8  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 8u;
      enum { I2C1_SCL = 4ul,  I2C3_SDA = 9ul,  I2S5_SD = 6ul,  SDIO_D4 = 12ul,  SPI5_MOSI = 6ul,  TIM10_CH1 = 3ul,  TIM4_CH3 = 2ul, }; 
    };

    struct PB9  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 9u;
      enum { I2C1_SDA = 4ul,  I2C2_SDA = 9ul,  I2S2_WS = 5ul,  SDIO_D5 = 12ul,  SPI2_NSS = 5ul,  TIM11_CH1 = 3ul,  TIM4_CH4 = 2ul, }; 
    };

    struct PC0  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 0u;
    };

    struct PC1  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 1u; 
    };

    struct PC10 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 10u;
      enum { I2S3_CK = 6ul,  SDIO_D2 = 12ul,  SPI3_SCK = 6ul, }; 
    };

    struct PC11 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 11u;
      enum { I2S3_ext_SD = 5ul,  SDIO_D3 = 12ul,  SPI3_MISO = 6ul, }; 
    };

    struct PC12 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 12u;
      enum { I2S3_SD = 6ul,  SDIO_CK = 12ul,  SPI3_MOSI = 6ul, }; 
    };

    struct PC13 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 13u;
    };

    struct PC14 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 14u;
    };

    struct PC15 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 15u;
    };

    struct PC2  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 2u;
      enum { I2S2_ext_SD = 6ul,  SPI2_MISO = 5ul, }; 
    };

    struct PC3  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 3u;
      enum { I2S2_SD = 5ul,  SPI2_MOSI = 5ul, }; 
    };

    struct PC4  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 4u;
    };

    struct PC5  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 5u;
    };

    struct PC6  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2S2_MCK = 5ul,  SDIO_D6 = 12ul,  TIM3_CH1 = 2ul,  USART6_TX = 8ul, }; 
    };

    struct PC7  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 7u;
      enum { I2S2_CK = 5ul,  I2S3_MCK = 6ul,  SDIO_D7 = 12ul,  SPI2_SCK = 5ul,  TIM3_CH2 = 2ul,  USART6_RX = 8ul, }; 
    };

    struct PC8  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 8u;
      enum { SDIO_D0 = 12ul,  TIM3_CH3 = 2ul,  USART6_CK = 8ul, }; 
    };

    struct PC9  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 9u;
      enum { I2C3_SDA = 4ul,  I2S_CKIN = 5ul,  RCC_MCO_2 = 0ul,  SDIO_D1 = 12ul,  TIM3_CH4 = 2ul, }; 
    };

    struct PD0  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 0u;
    };

    struct PD1  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 1u;
    };

    struct PD10 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 10u;
    };

    struct PD11 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 11u;
    };

    struct PD12 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 12u;
      enum { TIM4_CH1 = 2ul, }; 
    };

    struct PD13 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 13u;
      enum { TIM4_CH2 = 2ul, }; 
    };

    struct PD14 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 14u;
      enum { TIM4_CH3 = 2ul, }; 
    };

    struct PD15 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 15u;
      enum { TIM4_CH4 = 2ul, }; 
    };

    struct PD2  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 2u;
      enum { SDIO_CMD = 12ul,  TIM3_ETR = 2ul, }; 
    };

    struct PD3  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 3u;
      enum { I2S2_CK = 5ul,  SPI2_SCK = 5ul,  USART2_CTS = 7ul, }; 
    };

    struct PD4  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 4u;
      enum { USART2_RTS = 7ul, }; 
    };

    struct PD5  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 5u;
      enum { USART2_TX = 7ul, }; 
    };

    struct PD6  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2S3_SD = 5ul,  SPI3_MOSI = 5ul,  USART2_RX = 7ul, }; 
    };

    struct PD7  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 7u;
      enum { USART2_CK = 7ul, }; 
    };

    struct PD8  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 8u;
    };

    struct PD9  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 9u;
    };

    struct PE0  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 0u;
      enum { TIM4_ETR = 2ul, }; 
    };

    struct PE1  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 1u;
    };

    struct PE10 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 10u;
      enum { TIM1_CH2N = 1ul, }; 
    };

    struct PE11 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 11u;
      enum { I2S4_WS = 5ul,  I2S5_WS = 6ul,  SPI4_NSS = 5ul,  SPI5_NSS = 6ul,  TIM1_CH2 = 1ul, }; 
    };

    struct PE12 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 12u;
      enum { I2S4_CK = 5ul,  I2S5_CK = 6ul,  SPI4_SCK = 5ul,  SPI5_SCK = 6ul,  TIM1_CH3N = 1ul, }; 
    };

    struct PE13 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 13u;
      enum { SPI4_MISO = 5ul,  SPI5_MISO = 6ul,  TIM1_CH3 = 1ul, }; 
    };

    struct PE14 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 14u;
      enum { I2S4_SD = 5ul,  I2S5_SD = 6ul,  SPI4_MOSI = 5ul,  SPI5_MOSI = 6ul,  TIM1_CH4 = 1ul, }; 
    };

    struct PE15 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 15u;
      enum { TIM1_BKIN = 1ul, }; 
    };

    struct PE2  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 2u;
      enum { I2S4_CK = 5ul,  I2S5_CK = 6ul,  SPI4_SCK = 5ul,  SPI5_SCK = 6ul,  SYS_TRACECLK = 0ul, }; 
    };

    struct PE3  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 3u;
      enum { SYS_TRACED0 = 0ul, }; 
    };

    struct PE4  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 4u;
      enum { I2S4_WS = 5ul,  I2S5_WS = 6ul,  SPI4_NSS = 5ul,  SPI5_NSS = 6ul,  SYS_TRACED1 = 0ul, }; 
    };

    struct PE5  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 5u;
      enum { SPI4_MISO = 5ul,  SPI5_MISO = 6ul,  SYS_TRACED2 = 0ul,  TIM9_CH1 = 3ul, }; 
    };

    struct PE6  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2S4_SD = 5ul,  I2S5_SD = 6ul,  SPI4_MOSI = 5ul,  SPI5_MOSI = 6ul,  SYS_TRACED3 = 0ul,  TIM9_CH2 = 3ul, }; 
    };

    struct PE7  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 7u;
      enum { TIM1_ETR = 1ul, }; 
    };

    struct PE8  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 8u;
      enum { TIM1_CH1N = 1ul, }; 
    };

    struct PE9  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 9u;
      enum { TIM1_CH1 = 1ul, }; 
    };

    struct PH0  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 0u;
    };

    struct PH1  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 1u; 
    };
    
  } // inline namespace 
} // namespace mpp::io 
 
