/**
  ***********************************************************
  @file   /st/spec/STM32MPU_gpio_v1_0.hpp
  @brief  This is autogenerated file        
  ***********************************************************
**/

#pragma once


namespace mpp::io
{
  inline namespace STM32MPU_gpio_v1_0
  {
    enum class Port { 
      A = GPIOA_BASE,
      B = GPIOB_BASE,
      C = GPIOC_BASE,
      D = GPIOD_BASE,
      E = GPIOE_BASE,
      F = GPIOF_BASE,
      G = GPIOG_BASE,
      H = GPIOH_BASE,
      I = GPIOI_BASE,
      J = GPIOJ_BASE,
      K = GPIOK_BASE,
      Z = GPIOZ_BASE,
    };

    template< typename IO >
    constexpr bool IsValidIo()
    {
      switch(IO::kPort)
      { 
        case Port::A: return IO::kPin < 16u;
        case Port::B: return IO::kPin < 16u;
        case Port::C: return IO::kPin < 16u;
        case Port::D: return IO::kPin < 16u;
        case Port::E: return IO::kPin < 16u;
        case Port::F: return IO::kPin < 16u;
        case Port::G: return IO::kPin < 16u;
        case Port::H: return IO::kPin < 16u;
        case Port::I: return IO::kPin < 16u;
        case Port::J: return IO::kPin < 16u;
        case Port::K: return IO::kPin < 8u;
        case Port::Z: return IO::kPin < 8u;

        default: return false;
      }
    }


    

    struct PA0  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 0u;
      enum { ETH1_CRS = 11ul,  SAI2_SD_B = 10ul,  SDMMC2_CMD = 9ul,  TIM15_BKIN = 4ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM5_CH1 = 2ul,  TIM8_ETR = 3ul,  UART4_TX = 8ul,  USART2_CTS = 7ul,  USART2_NSS = 7ul, }; 
    };

    struct PA1  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 1u;
      enum { ETH1_CLK = 0ul,  ETH1_REF_CLK = 11ul,  ETH1_RX_CLK = 11ul,  LPTIM3_OUT = 3ul,  LTDC_R2 = 14ul,  QUADSPI_BK1_IO3 = 9ul,  SAI2_MCLK_B = 10ul,  TIM15_CH1N = 4ul,  TIM2_CH2 = 1ul,  TIM5_CH2 = 2ul,  UART4_RX = 8ul,  USART2_DE = 7ul,  USART2_RTS = 7ul, }; 
    };

    struct PA10 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 10u;
      enum { DCMI_D1 = 13ul,  I2S3_WS = 5ul,  LTDC_B1 = 14ul,  MDIOS_MDIO = 11ul,  SAI4_FS_B = 12ul,  SPI3_NSS = 5ul,  TIM1_CH3 = 1ul,  USART1_RX = 7ul, }; 
    };

    struct PA11 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 11u;
      enum { FDCAN1_RX = 9ul,  I2C5_SCL = 4ul,  I2C6_SCL = 2ul,  I2S2_WS = 5ul,  LTDC_R4 = 14ul,  SPI2_NSS = 5ul,  TIM1_CH4 = 1ul,  UART4_RX = 6ul,  USART1_CTS = 7ul,  USART1_NSS = 7ul, }; 
    };

    struct PA12 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 12u;
      enum { FDCAN1_TX = 9ul,  I2C5_SDA = 4ul,  I2C6_SDA = 2ul,  LTDC_R5 = 14ul,  SAI2_FS_B = 8ul,  TIM1_ETR = 1ul,  UART4_TX = 6ul,  USART1_DE = 7ul,  USART1_RTS = 7ul, }; 
    };

    struct PA13 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 13u;
      enum { DEBUG_DBTRGI = 1ul,  DEBUG_DBTRGO = 0ul,  RCC_MCO_1 = 2ul,  UART4_TX = 8ul, }; 
    };

    struct PA14 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 14u;
      enum { DEBUG_DBTRGI = 1ul,  DEBUG_DBTRGO = 0ul,  RCC_MCO_2 = 2ul, }; 
    };

    struct PA15 
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 15u;
      enum { CEC_IO = 4ul,  DEBUG_DBTRGI = 0ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  LTDC_R1 = 14ul,  SAI4_D2 = 2ul,  SAI4_FS_A = 12ul,  SDMMC1_CDIR = 3ul,  SDMMC1_D5 = 11ul,  SDMMC2_CDIR = 10ul,  SDMMC2_D5 = 9ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SPI6_NSS = 7ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  UART4_DE = 8ul,  UART4_RTS = 8ul,  UART7_TX = 13ul, }; 
    };

    struct PA2  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 2u;
      enum { ETH1_MDIO = 11ul,  LPTIM4_OUT = 3ul,  LTDC_R1 = 14ul,  MDIOS_MDIO = 12ul,  SAI2_SCK_B = 8ul,  SDMMC2_D0DIR = 10ul,  TIM15_CH1 = 4ul,  TIM2_CH3 = 1ul,  TIM5_CH3 = 2ul,  USART2_TX = 7ul, }; 
    };

    struct PA3  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 3u;
      enum { ETH1_COL = 11ul,  LPTIM5_OUT = 3ul,  LTDC_B2 = 9ul,  LTDC_B5 = 14ul,  TIM15_CH2 = 4ul,  TIM2_CH4 = 1ul,  TIM5_CH4 = 2ul,  USART2_RX = 7ul, }; 
    };

    struct PA4  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 4u;
      enum { DCMI_HSYNC = 13ul,  HDP_HDP0 = 0ul,  I2S1_WS = 5ul,  I2S3_WS = 6ul,  LTDC_VSYNC = 14ul,  SAI4_D2 = 4ul,  SAI4_FS_A = 12ul,  SPI1_NSS = 5ul,  SPI3_NSS = 6ul,  SPI6_NSS = 8ul,  TIM5_ETR = 2ul,  USART2_CK = 7ul, }; 
    };

    struct PA5  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2S1_CK = 5ul,  LTDC_R4 = 14ul,  SAI4_CK1 = 4ul,  SAI4_MCLK_A = 12ul,  SPI1_SCK = 5ul,  SPI6_SCK = 8ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM8_CH1N = 3ul, }; 
    };

    struct PA6  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_PIXCLK = 13ul,  I2S1_SDI = 5ul,  LTDC_G2 = 14ul,  MDIOS_MDC = 11ul,  SAI4_CK2 = 4ul,  SAI4_SCK_A = 12ul,  SPI1_MISO = 5ul,  SPI6_MISO = 8ul,  TIM13_CH1 = 9ul,  TIM1_BKIN = 1ul,  TIM3_CH1 = 2ul,  TIM8_BKIN = 3ul, }; 
    };

    struct PA7  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 7u;
      enum { ETH1_CRS_DV = 11ul,  ETH1_RX_CTL = 11ul,  ETH1_RX_DV = 11ul,  I2S1_SDO = 5ul,  QUADSPI_CLK = 10ul,  SAI4_D1 = 4ul,  SAI4_SD_A = 12ul,  SPI1_MOSI = 5ul,  SPI6_MOSI = 8ul,  TIM14_CH1 = 9ul,  TIM1_CH1N = 1ul,  TIM3_CH2 = 2ul,  TIM8_CH1N = 3ul, }; 
    };

    struct PA8  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 8u;
      enum { I2C3_SCL = 4ul,  I2S3_SDO = 5ul,  LTDC_R6 = 14ul,  RCC_MCO_1 = 0ul,  SAI4_SD_B = 12ul,  SDMMC2_CKIN = 8ul,  SDMMC2_D4 = 9ul,  SPI3_MOSI = 5ul,  TIM1_CH1 = 1ul,  TIM8_BKIN2 = 3ul,  UART7_RX = 13ul,  USART1_CK = 7ul,  USB_OTG_FS_SOF = 10ul,  USB_OTG_HS_SOF = 10ul, }; 
    };

    struct PA9  
    {
      constexpr static Port kPort = Port::A;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_D0 = 13ul,  I2C3_SMBA = 4ul,  I2S2_CK = 5ul,  LTDC_R5 = 14ul,  SDMMC2_CDIR = 8ul,  SDMMC2_D5 = 10ul,  SPI2_SCK = 5ul,  TIM1_CH2 = 1ul,  USART1_TX = 7ul, }; 
    };

    struct PB0  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 0u;
      enum { DFSDM1_CKOUT = 6ul,  ETH1_RXD2 = 11ul,  LTDC_G1 = 14ul,  LTDC_R3 = 9ul,  MDIOS_MDIO = 12ul,  TIM1_CH2N = 1ul,  TIM3_CH3 = 2ul,  TIM8_CH2N = 3ul,  UART4_CTS = 8ul, }; 
    };

    struct PB1  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 1u;
      enum { DFSDM1_DATIN1 = 6ul,  ETH1_RXD3 = 11ul,  LTDC_G0 = 14ul,  LTDC_R6 = 9ul,  MDIOS_MDC = 12ul,  TIM1_CH3N = 1ul,  TIM3_CH4 = 2ul,  TIM8_CH3N = 3ul, }; 
    };

    struct PB10 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 10u;
      enum { DFSDM1_DATIN7 = 6ul,  ETH1_RX_ER = 11ul,  I2C2_SCL = 4ul,  I2S2_CK = 5ul,  LPTIM2_IN1 = 3ul,  LTDC_G4 = 14ul,  QUADSPI_BK1_NCS = 9ul,  SPI2_SCK = 5ul,  TIM2_CH3 = 1ul,  USART3_TX = 7ul, }; 
    };

    struct PB11 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 11u;
      enum { DFSDM1_CKIN7 = 6ul,  DSIHOST_TE = 13ul,  ETH1_TX_CTL = 11ul,  ETH1_TX_EN = 11ul,  I2C2_SDA = 4ul,  LPTIM2_ETR = 3ul,  LTDC_G5 = 14ul,  TIM2_CH4 = 1ul,  USART3_RX = 7ul, }; 
    };

    struct PB12 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 12u;
      enum { DFSDM1_DATIN1 = 6ul,  ETH1_TXD0 = 11ul,  FDCAN2_RX = 9ul,  I2C2_SMBA = 4ul,  I2C6_SMBA = 2ul,  I2S2_WS = 5ul,  SPI2_NSS = 5ul,  TIM1_BKIN = 1ul,  UART5_RX = 14ul,  USART3_CK = 7ul,  USART3_RX = 8ul, }; 
    };

    struct PB13 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 13u;
      enum { DFSDM1_CKIN1 = 6ul,  DFSDM1_CKOUT = 3ul,  ETH1_TXD1 = 11ul,  FDCAN2_TX = 9ul,  I2S2_CK = 5ul,  LPTIM2_OUT = 4ul,  SPI2_SCK = 5ul,  TIM1_CH1N = 1ul,  UART5_TX = 14ul,  USART3_CTS = 7ul,  USART3_NSS = 7ul, }; 
    };

    struct PB14 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 14u;
      enum { DFSDM1_DATIN2 = 6ul,  I2S2_SDI = 5ul,  SDMMC2_D0 = 9ul,  SPI2_MISO = 5ul,  TIM12_CH1 = 2ul,  TIM1_CH2N = 1ul,  TIM8_CH2N = 3ul,  USART1_TX = 4ul,  USART3_DE = 7ul,  USART3_RTS = 7ul, }; 
    };

    struct PB15 
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 15u;
      enum { DFSDM1_CKIN2 = 6ul,  I2S2_SDO = 5ul,  RTC_REFIN = 0ul,  SDMMC2_D1 = 9ul,  SPI2_MOSI = 5ul,  TIM12_CH2 = 2ul,  TIM1_CH3N = 1ul,  TIM8_CH3N = 3ul,  USART1_RX = 4ul, }; 
    };

    struct PB2  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 2u;
      enum { DEBUG_TRACED4 = 0ul,  DFSDM1_CKIN1 = 3ul,  I2S3_SDO = 7ul,  I2S_CKIN = 5ul,  QUADSPI_CLK = 9ul,  RTC_OUT2 = 1ul,  RTC_OUT_ALARM2 = 1ul,  RTC_OUT_CALIB2 = 1ul,  SAI1_D1 = 2ul,  SAI1_SD_A = 6ul,  SPI3_MOSI = 7ul,  UART4_RX = 8ul,  USART1_RX = 4ul, }; 
    };

    struct PB3  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 3u;
      enum { DEBUG_TRACED9 = 0ul,  I2S1_CK = 5ul,  I2S3_CK = 6ul,  SAI4_CK1 = 4ul,  SAI4_MCLK_A = 12ul,  SDMMC2_D2 = 9ul,  SPI1_SCK = 5ul,  SPI3_SCK = 6ul,  SPI6_SCK = 8ul,  TIM2_CH2 = 1ul,  UART7_RX = 13ul, }; 
    };

    struct PB4  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 4u;
      enum { DEBUG_TRACED8 = 0ul,  I2S1_SDI = 5ul,  I2S2_WS = 7ul,  I2S3_SDI = 6ul,  SAI4_CK2 = 4ul,  SAI4_SCK_A = 12ul,  SDMMC2_D3 = 9ul,  SPI1_MISO = 5ul,  SPI2_NSS = 7ul,  SPI3_MISO = 6ul,  SPI6_MISO = 8ul,  TIM16_BKIN = 1ul,  TIM3_CH1 = 2ul,  UART7_TX = 13ul, }; 
    };

    struct PB5  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 5u;
      enum { DCMI_D10 = 13ul,  ETH1_CLK = 0ul,  ETH1_PPS_OUT = 11ul,  FDCAN2_RX = 9ul,  I2C1_SMBA = 4ul,  I2C4_SMBA = 6ul,  I2S1_SDO = 5ul,  I2S3_SDO = 7ul,  LTDC_G7 = 14ul,  SAI4_D1 = 3ul,  SAI4_SD_A = 10ul,  SPI1_MOSI = 5ul,  SPI3_MOSI = 7ul,  SPI6_MOSI = 8ul,  TIM17_BKIN = 1ul,  TIM3_CH2 = 2ul,  UART5_RX = 12ul, }; 
    };

    struct PB6  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 6u;
      enum { CEC_IO = 5ul,  DCMI_D5 = 13ul,  DFSDM1_DATIN5 = 11ul,  FDCAN2_TX = 9ul,  I2C1_SCL = 4ul,  I2C4_SCL = 6ul,  QUADSPI_BK1_NCS = 10ul,  TIM16_CH1N = 1ul,  TIM4_CH1 = 2ul,  UART5_TX = 12ul,  USART1_TX = 7ul, }; 
    };

    struct PB7  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 7u;
      enum { DCMI_VSYNC = 13ul,  DFSDM1_CKIN5 = 11ul,  FMC_NL = 12ul,  I2C1_SDA = 4ul,  I2C4_SDA = 6ul,  SDMMC2_D1 = 10ul,  TIM17_CH1N = 1ul,  TIM4_CH2 = 2ul,  USART1_RX = 7ul, }; 
    };

    struct PB8  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 8u;
      enum { DCMI_D6 = 13ul,  DFSDM1_CKIN7 = 3ul,  ETH1_TXD3 = 11ul,  FDCAN1_RX = 9ul,  HDP_HDP6 = 0ul,  I2C1_SCL = 4ul,  I2C4_SCL = 6ul,  LTDC_B6 = 14ul,  SDMMC1_CKIN = 5ul,  SDMMC1_D4 = 12ul,  SDMMC2_CKIN = 7ul,  SDMMC2_D4 = 10ul,  TIM16_CH1 = 1ul,  TIM4_CH3 = 2ul,  UART4_RX = 8ul, }; 
    };

    struct PB9  
    {
      constexpr static Port kPort = Port::B;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_D7 = 13ul,  DFSDM1_DATIN7 = 3ul,  FDCAN1_TX = 9ul,  HDP_HDP7 = 0ul,  I2C1_SDA = 4ul,  I2C4_SDA = 6ul,  I2S2_WS = 5ul,  LTDC_B7 = 14ul,  SDMMC1_CDIR = 11ul,  SDMMC1_D5 = 12ul,  SDMMC2_CDIR = 7ul,  SDMMC2_D5 = 10ul,  SPI2_NSS = 5ul,  TIM17_CH1 = 1ul,  TIM4_CH4 = 2ul,  UART4_TX = 8ul, }; 
    };

    struct PC0  
    {
      constexpr static Port kPort = Port::C;
    constexpr static std::uint32_t kPin = 0u;
      enum { DFSDM1_CKIN0 = 3ul,  DFSDM1_DATIN4 = 6ul,  LPTIM2_IN2 = 4ul,  LTDC_R5 = 14ul,  QUADSPI_BK2_NCS = 10ul,  SAI2_FS_B = 8ul, }; 
    };

    struct PC1  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 1u;
      enum { DEBUG_TRACED0 = 0ul,  DFSDM1_CKIN4 = 4ul,  DFSDM1_DATIN0 = 3ul,  ETH1_MDC = 11ul,  I2S2_SDO = 5ul,  MDIOS_MDC = 12ul,  SAI1_D1 = 2ul,  SAI1_SD_A = 6ul,  SDMMC2_CK = 9ul,  SPI2_MOSI = 5ul, }; 
    };

    struct PC10 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 10u;
      enum { DCMI_D8 = 13ul,  DEBUG_TRACED2 = 0ul,  DFSDM1_CKIN5 = 3ul,  I2S3_CK = 6ul,  LTDC_R2 = 14ul,  QUADSPI_BK1_IO1 = 9ul,  SAI4_MCLK_B = 10ul,  SDMMC1_D2 = 12ul,  SPI3_SCK = 6ul,  UART4_TX = 8ul,  USART3_TX = 7ul, }; 
    };

    struct PC11 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 11u;
      enum { DCMI_D4 = 13ul,  DEBUG_TRACED3 = 0ul,  DFSDM1_DATIN5 = 3ul,  I2S3_SDI = 6ul,  QUADSPI_BK2_NCS = 9ul,  SAI4_SCK_B = 10ul,  SDMMC1_D3 = 12ul,  SPI3_MISO = 6ul,  UART4_RX = 8ul,  USART3_RX = 7ul, }; 
    };

    struct PC12 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 12u;
      enum { DCMI_D9 = 13ul,  DEBUG_TRACECLK = 0ul,  I2S3_SDO = 6ul,  RCC_MCO_2 = 1ul,  SAI4_D3 = 2ul,  SAI4_SD_B = 10ul,  SDMMC1_CK = 12ul,  SPI3_MOSI = 6ul,  UART5_TX = 8ul,  USART3_CK = 7ul, }; 
    };

    struct PC13 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 13u;
      enum {}; 
    };

    struct PC14 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 14u;
      enum {}; 
    };

    struct PC15 
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 15u;
      enum {}; 
    };

    struct PC2  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 2u;
      enum { DCMI_PIXCLK = 13ul,  DFSDM1_CKIN1 = 3ul,  DFSDM1_CKOUT = 6ul,  ETH1_TXD2 = 11ul,  I2S2_SDI = 5ul,  SPI2_MISO = 5ul, }; 
    };

    struct PC3  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 3u;
      enum { DEBUG_TRACECLK = 0ul,  DFSDM1_DATIN1 = 3ul,  ETH1_TX_CLK = 11ul,  I2S2_SDO = 5ul,  SPI2_MOSI = 5ul, }; 
    };

    struct PC4  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 4u;
      enum { DFSDM1_CKIN2 = 3ul,  ETH1_RXD0 = 11ul,  I2S1_MCK = 5ul,  SPDIFRX_IN2 = 9ul, }; 
    };

    struct PC5  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 5u;
      enum { DFSDM1_DATIN2 = 3ul,  ETH1_RXD1 = 11ul,  SAI1_D3 = 2ul,  SAI1_D4 = 6ul,  SAI4_D3 = 12ul,  SAI4_D4 = 4ul,  SPDIFRX_IN3 = 9ul, }; 
    };

    struct PC6  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D0 = 13ul,  DFSDM1_CKIN3 = 4ul,  DSIHOST_TE = 11ul,  HDP_HDP1 = 0ul,  I2S2_MCK = 5ul,  LTDC_HSYNC = 14ul,  SDMMC1_D0DIR = 8ul,  SDMMC1_D6 = 12ul,  SDMMC2_D0DIR = 9ul,  SDMMC2_D6 = 10ul,  TIM3_CH1 = 2ul,  TIM8_CH1 = 3ul,  USART6_TX = 7ul, }; 
    };

    struct PC7  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 7u;
      enum { DCMI_D1 = 13ul,  DFSDM1_DATIN3 = 4ul,  HDP_HDP4 = 0ul,  I2S3_MCK = 6ul,  LTDC_G6 = 14ul,  SDMMC1_D123DIR = 8ul,  SDMMC1_D7 = 12ul,  SDMMC2_D123DIR = 9ul,  SDMMC2_D7 = 10ul,  TIM3_CH2 = 2ul,  TIM8_CH2 = 3ul,  USART6_RX = 7ul, }; 
    };

    struct PC8  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 8u;
      enum { DCMI_D2 = 13ul,  DEBUG_TRACED0 = 0ul,  SDMMC1_D0 = 12ul,  TIM3_CH3 = 2ul,  TIM8_CH3 = 3ul,  UART4_TX = 6ul,  UART5_DE = 8ul,  UART5_RTS = 8ul,  USART6_CK = 7ul, }; 
    };

    struct PC9  
    {
      constexpr static Port kPort = Port::C;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_D3 = 13ul,  DEBUG_TRACED1 = 0ul,  I2C3_SDA = 4ul,  I2S_CKIN = 5ul,  LTDC_B2 = 14ul,  QUADSPI_BK1_IO0 = 9ul,  SDMMC1_D1 = 12ul,  TIM3_CH4 = 2ul,  TIM8_CH4 = 3ul,  UART5_CTS = 8ul, }; 
    };

    struct PD0  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 0u;
      enum { DFSDM1_CKIN6 = 3ul,  DFSDM1_DATIN7 = 11ul,  FDCAN1_RX = 9ul,  FMC_D2 = 12ul,  FMC_DA2 = 12ul,  I2C5_SDA = 4ul,  I2C6_SDA = 2ul,  SAI3_SCK_A = 6ul,  SDMMC3_CMD = 10ul,  UART4_RX = 8ul, }; 
    };

    struct PD1  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 1u;
      enum { DFSDM1_CKIN7 = 11ul,  DFSDM1_DATIN6 = 3ul,  FDCAN1_TX = 9ul,  FMC_D3 = 12ul,  FMC_DA3 = 12ul,  I2C5_SCL = 4ul,  I2C6_SCL = 2ul,  SAI3_SD_A = 6ul,  SDMMC3_D0 = 10ul,  UART4_TX = 8ul, }; 
    };

    struct PD10 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 10u;
      enum { DFSDM1_CKOUT = 3ul,  FMC_D15 = 12ul,  FMC_DA15 = 12ul,  I2C5_SMBA = 4ul,  I2S3_SDI = 5ul,  LTDC_B3 = 14ul,  RTC_REFIN = 0ul,  SAI3_FS_B = 6ul,  SPI3_MISO = 5ul,  TIM16_BKIN = 1ul,  USART3_CK = 7ul, }; 
    };

    struct PD11 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 11u;
      enum { FMC_A16 = 12ul,  FMC_CLE = 12ul,  I2C1_SMBA = 5ul,  I2C4_SMBA = 4ul,  LPTIM2_IN2 = 3ul,  QUADSPI_BK1_IO0 = 9ul,  SAI2_SD_A = 10ul,  USART3_CTS = 7ul,  USART3_NSS = 7ul, }; 
    };

    struct PD12 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 12u;
      enum { FMC_A17 = 12ul,  FMC_ALE = 12ul,  I2C1_SCL = 5ul,  I2C4_SCL = 4ul,  LPTIM1_IN1 = 1ul,  LPTIM2_IN1 = 3ul,  QUADSPI_BK1_IO1 = 9ul,  SAI2_FS_A = 10ul,  TIM4_CH1 = 2ul,  USART3_DE = 7ul,  USART3_RTS = 7ul, }; 
    };

    struct PD13 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 13u;
      enum { DSIHOST_TE = 13ul,  FMC_A18 = 12ul,  I2C1_SDA = 5ul,  I2C4_SDA = 4ul,  I2S3_MCK = 6ul,  LPTIM1_OUT = 1ul,  QUADSPI_BK1_IO3 = 9ul,  SAI2_SCK_A = 10ul,  TIM4_CH2 = 2ul, }; 
    };

    struct PD14 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 14u;
      enum { FMC_D0 = 12ul,  FMC_DA0 = 12ul,  SAI3_MCLK_B = 6ul,  TIM4_CH3 = 2ul,  UART8_CTS = 8ul, }; 
    };

    struct PD15 
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 15u;
      enum { FMC_D1 = 12ul,  FMC_DA1 = 12ul,  LTDC_R1 = 14ul,  SAI3_MCLK_A = 6ul,  TIM4_CH4 = 2ul,  UART8_CTS = 8ul, }; 
    };

    struct PD2  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 2u;
      enum { DCMI_D11 = 13ul,  I2C5_SMBA = 4ul,  SDMMC1_CMD = 12ul,  TIM3_ETR = 2ul,  UART4_RX = 6ul,  UART5_RX = 8ul, }; 
    };

    struct PD3  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 3u;
      enum { DCMI_D5 = 13ul,  DFSDM1_CKOUT = 3ul,  DFSDM1_DATIN0 = 6ul,  FMC_CLK = 12ul,  HDP_HDP5 = 0ul,  I2S2_CK = 5ul,  LTDC_G7 = 14ul,  SDMMC1_D123DIR = 8ul,  SDMMC1_D7 = 11ul,  SDMMC2_D123DIR = 10ul,  SDMMC2_D7 = 9ul,  SPI2_SCK = 5ul,  USART2_CTS = 7ul,  USART2_NSS = 7ul, }; 
    };

    struct PD4  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 4u;
      enum { DFSDM1_CKIN0 = 11ul,  FMC_NOE = 12ul,  SAI3_FS_A = 6ul,  SDMMC3_D1 = 10ul,  USART2_DE = 7ul,  USART2_RTS = 7ul, }; 
    };

    struct PD5  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 5u;
      enum { FMC_NWE = 12ul,  SDMMC3_D2 = 10ul,  USART2_TX = 7ul, }; 
    };

    struct PD6  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D10 = 13ul,  DFSDM1_CKIN4 = 3ul,  DFSDM1_DATIN1 = 4ul,  FMC_NWAIT = 12ul,  I2S3_SDO = 5ul,  LTDC_B2 = 14ul,  SAI1_D1 = 2ul,  SAI1_SD_A = 6ul,  SPI3_MOSI = 5ul,  TIM16_CH1N = 1ul,  USART2_RX = 7ul, }; 
    };

    struct PD7  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 7u;
      enum { DEBUG_TRACED6 = 0ul,  DFSDM1_CKIN1 = 6ul,  DFSDM1_DATIN4 = 3ul,  FMC_NE1 = 12ul,  I2C2_SCL = 4ul,  SDMMC3_D3 = 10ul,  SPDIFRX_IN0 = 9ul,  USART2_CK = 7ul, }; 
    };

    struct PD8  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 8u;
      enum { DFSDM1_CKIN3 = 3ul,  FMC_D13 = 12ul,  FMC_DA13 = 12ul,  LTDC_B7 = 14ul,  SAI3_SCK_B = 6ul,  SPDIFRX_IN1 = 9ul,  USART3_TX = 7ul, }; 
    };

    struct PD9  
    {
      constexpr static Port kPort = Port::D;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_HSYNC = 13ul,  DFSDM1_DATIN3 = 3ul,  FMC_D14 = 12ul,  FMC_DA14 = 12ul,  LTDC_B0 = 14ul,  SAI3_SD_B = 6ul,  USART3_RX = 7ul, }; 
    };

    struct PE0  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 0u;
      enum { DCMI_D2 = 13ul,  FMC_NBL0 = 12ul,  I2S3_CK = 5ul,  LPTIM1_ETR = 1ul,  LPTIM2_ETR = 4ul,  SAI2_MCLK_A = 10ul,  SAI4_MCLK_B = 6ul,  SPI3_SCK = 5ul,  TIM4_ETR = 2ul,  UART8_RX = 8ul, }; 
    };

    struct PE1  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 1u;
      enum { DCMI_D3 = 13ul,  FMC_NBL1 = 12ul,  I2S2_MCK = 5ul,  LPTIM1_IN2 = 1ul,  SAI3_SD_B = 6ul,  UART8_TX = 8ul, }; 
    };

    struct PE10 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 10u;
      enum { DFSDM1_DATIN4 = 3ul,  FMC_D7 = 12ul,  FMC_DA7 = 12ul,  QUADSPI_BK2_IO3 = 10ul,  TIM1_CH2N = 1ul,  UART7_CTS = 7ul, }; 
    };

    struct PE11 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 11u;
      enum { DCMI_D4 = 13ul,  DFSDM1_CKIN4 = 3ul,  FMC_D8 = 12ul,  FMC_DA8 = 12ul,  LTDC_G3 = 14ul,  SAI2_SD_B = 10ul,  SPI4_NSS = 5ul,  TIM1_CH2 = 1ul,  USART6_CK = 7ul, }; 
    };

    struct PE12 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 12u;
      enum { DFSDM1_DATIN5 = 3ul,  FMC_D9 = 12ul,  FMC_DA9 = 12ul,  LTDC_B4 = 14ul,  SAI2_SCK_B = 10ul,  SDMMC1_D0DIR = 8ul,  SPI4_SCK = 5ul,  TIM1_CH3N = 1ul, }; 
    };

    struct PE13 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 13u;
      enum { DCMI_D6 = 13ul,  DFSDM1_CKIN5 = 3ul,  FMC_D10 = 12ul,  FMC_DA10 = 12ul,  HDP_HDP2 = 0ul,  LTDC_DE = 14ul,  SAI2_FS_B = 10ul,  SPI4_MISO = 5ul,  TIM1_CH3 = 1ul, }; 
    };

    struct PE14 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 14u;
      enum { FMC_D11 = 12ul,  FMC_DA11 = 12ul,  LTDC_CLK = 14ul,  LTDC_G0 = 13ul,  SAI2_MCLK_B = 10ul,  SDMMC1_D123DIR = 11ul,  SPI4_MOSI = 5ul,  TIM1_CH4 = 1ul,  UART8_DE = 8ul,  UART8_RTS = 8ul, }; 
    };

    struct PE15 
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 15u;
      enum { FMC_D12 = 12ul,  FMC_DA12 = 12ul,  FMC_NCE2 = 10ul,  HDP_HDP3 = 0ul,  LTDC_R7 = 14ul,  TIM15_BKIN = 4ul,  TIM1_BKIN = 1ul,  UART8_CTS = 8ul,  USART2_CTS = 7ul,  USART2_NSS = 7ul, }; 
    };

    struct PE2  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 2u;
      enum { DEBUG_TRACECLK = 0ul,  ETH1_TXD3 = 11ul,  FMC_A23 = 12ul,  I2C4_SCL = 4ul,  QUADSPI_BK1_IO2 = 9ul,  SAI1_CK1 = 2ul,  SAI1_MCLK_A = 6ul,  SPI4_SCK = 5ul, }; 
    };

    struct PE3  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 3u;
      enum { DEBUG_TRACED0 = 0ul,  FMC_A19 = 12ul,  SAI1_SD_B = 6ul,  SDMMC2_CK = 9ul,  TIM15_BKIN = 4ul, }; 
    };

    struct PE4  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 4u;
      enum { DCMI_D4 = 13ul,  DEBUG_TRACED1 = 0ul,  DFSDM1_DATIN3 = 3ul,  FMC_A20 = 12ul,  LTDC_B0 = 14ul,  SAI1_D2 = 2ul,  SAI1_FS_A = 6ul,  SDMMC1_CKIN = 8ul,  SDMMC1_D4 = 11ul,  SDMMC2_CKIN = 7ul,  SDMMC2_D4 = 9ul,  SPI4_NSS = 5ul,  TIM15_CH1N = 4ul, }; 
    };

    struct PE5  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 5u;
      enum { DCMI_D6 = 13ul,  DEBUG_TRACED3 = 0ul,  DFSDM1_CKIN3 = 3ul,  FMC_A21 = 12ul,  LTDC_G0 = 14ul,  SAI1_CK2 = 2ul,  SAI1_SCK_A = 6ul,  SDMMC1_D0DIR = 8ul,  SDMMC1_D6 = 11ul,  SDMMC2_D0DIR = 7ul,  SDMMC2_D6 = 9ul,  SPI4_MISO = 5ul,  TIM15_CH1 = 4ul, }; 
    };

    struct PE6  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D7 = 13ul,  DEBUG_TRACED2 = 0ul,  FMC_A22 = 12ul,  LTDC_G1 = 14ul,  SAI1_D1 = 2ul,  SAI1_SD_A = 6ul,  SAI2_MCLK_B = 10ul,  SDMMC1_D2 = 8ul,  SDMMC2_D0 = 7ul,  SPI4_MOSI = 5ul,  TIM15_CH2 = 4ul,  TIM1_BKIN2 = 1ul, }; 
    };

    struct PE7  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 7u;
      enum { DFSDM1_DATIN2 = 3ul,  FMC_D4 = 12ul,  FMC_DA4 = 12ul,  QUADSPI_BK2_IO0 = 10ul,  TIM1_ETR = 1ul,  TIM3_ETR = 2ul,  UART7_RX = 7ul, }; 
    };

    struct PE8  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 8u;
      enum { DFSDM1_CKIN2 = 3ul,  FMC_D5 = 12ul,  FMC_DA5 = 12ul,  QUADSPI_BK2_IO1 = 10ul,  TIM1_CH1N = 1ul,  UART7_TX = 7ul, }; 
    };

    struct PE9  
    {
      constexpr static Port kPort = Port::E;
      constexpr static std::uint32_t kPin = 9u;
      enum { DFSDM1_CKOUT = 3ul,  FMC_D6 = 12ul,  FMC_DA6 = 12ul,  QUADSPI_BK2_IO2 = 10ul,  TIM1_CH1 = 1ul,  UART7_DE = 7ul,  UART7_RTS = 7ul, }; 
    };

    struct PF0  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 0u;
      enum { FMC_A0 = 12ul,  I2C2_SDA = 4ul,  SDMMC3_CKIN = 10ul,  SDMMC3_D0 = 9ul, }; 
    };

    struct PF1  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 1u;
      enum { FMC_A1 = 12ul,  I2C2_SCL = 4ul,  SDMMC3_CDIR = 10ul,  SDMMC3_CMD = 9ul, }; 
    };

    struct PF10 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 10u;
      enum { DCMI_D11 = 13ul,  LTDC_DE = 14ul,  QUADSPI_CLK = 9ul,  SAI1_D3 = 2ul,  SAI1_D4 = 6ul,  SAI4_D3 = 12ul,  SAI4_D4 = 3ul,  TIM16_BKIN = 1ul, }; 
    };

    struct PF11 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 11u;
      enum { DCMI_D12 = 13ul,  LTDC_G5 = 14ul,  SAI2_SD_B = 10ul,  SPI5_MOSI = 5ul, }; 
    };

    struct PF12 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 12u;
      enum { DEBUG_TRACED4 = 0ul,  ETH1_RXD4 = 11ul,  FMC_A6 = 12ul, }; 
    };

    struct PF13 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 13u;
      enum { DEBUG_TRACED5 = 0ul,  DFSDM1_DATIN3 = 6ul,  DFSDM1_DATIN6 = 3ul,  ETH1_RXD5 = 11ul,  FMC_A7 = 12ul,  I2C1_SMBA = 5ul,  I2C4_SMBA = 4ul, }; 
    };

    struct PF14 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 14u;
      enum { DEBUG_TRACED6 = 0ul,  DFSDM1_CKIN6 = 3ul,  ETH1_RXD6 = 11ul,  FMC_A8 = 12ul,  I2C1_SCL = 5ul,  I2C4_SCL = 4ul, }; 
    };

    struct PF15 
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 15u;
      enum { DEBUG_TRACED7 = 0ul,  ETH1_RXD7 = 11ul,  FMC_A9 = 12ul,  I2C1_SDA = 5ul,  I2C4_SDA = 4ul, }; 
    };

    struct PF2  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 2u;
      enum { FMC_A2 = 12ul,  I2C2_SMBA = 4ul,  SDMMC1_D0DIR = 11ul,  SDMMC2_D0DIR = 9ul,  SDMMC3_D0DIR = 10ul, }; 
    };

    struct PF3  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 3u;
      enum { ETH1_TX_ER = 11ul,  FMC_A3 = 12ul, }; 
    };

    struct PF4  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 4u;
      enum { FMC_A4 = 12ul,  SDMMC3_D1 = 9ul,  SDMMC3_D123DIR = 10ul,  USART2_RX = 7ul, }; 
    };

    struct PF5  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 5u;
      enum { FMC_A5 = 12ul,  SDMMC3_D2 = 9ul,  USART2_TX = 7ul, }; 
    };

    struct PF6  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 6u;
      enum { QUADSPI_BK1_IO3 = 9ul,  SAI1_SD_B = 6ul,  SAI4_SCK_B = 12ul,  SPI5_NSS = 5ul,  TIM16_CH1 = 1ul,  UART7_RX = 7ul, }; 
    };

    struct PF7  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 7u;
      enum { QUADSPI_BK1_IO2 = 9ul,  SAI1_MCLK_B = 6ul,  SPI5_SCK = 5ul,  TIM17_CH1 = 1ul,  UART7_TX = 7ul, }; 
    };

    struct PF8  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 8u;
      enum { DEBUG_TRACED12 = 0ul,  QUADSPI_BK1_IO0 = 10ul,  SAI1_SCK_B = 6ul,  SPI5_MISO = 5ul,  TIM13_CH1 = 9ul,  TIM16_CH1N = 1ul,  UART7_DE = 7ul,  UART7_RTS = 7ul, }; 
    };

    struct PF9  
    {
      constexpr static Port kPort = Port::F;
      constexpr static std::uint32_t kPin = 9u;
      enum { DEBUG_TRACED13 = 0ul,  QUADSPI_BK1_IO1 = 10ul,  SAI1_FS_B = 6ul,  SPI5_MOSI = 5ul,  TIM14_CH1 = 9ul,  TIM17_CH1N = 1ul,  UART7_CTS = 7ul, }; 
    };

    struct PG0  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 0u;
      enum { DEBUG_TRACED0 = 0ul,  DFSDM1_DATIN0 = 3ul,  ETH1_TXD4 = 11ul,  FMC_A10 = 12ul, }; 
    };

    struct PG1  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 1u;
      enum { DEBUG_TRACED1 = 0ul,  ETH1_TXD5 = 11ul,  FMC_A11 = 12ul, }; 
    };

    struct PG10 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 10u;
      enum { DCMI_D2 = 13ul,  DEBUG_TRACED10 = 0ul,  FMC_NE3 = 12ul,  LTDC_B2 = 14ul,  LTDC_G3 = 9ul,  QUADSPI_BK2_IO2 = 11ul,  SAI2_SD_B = 10ul,  UART8_CTS = 8ul, }; 
    };

    struct PG11 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 11u;
      enum { DCMI_D3 = 13ul,  DEBUG_TRACED11 = 0ul,  ETH1_TX_CTL = 11ul,  ETH1_TX_EN = 11ul,  LTDC_B3 = 14ul,  SPDIFRX_IN0 = 8ul,  UART4_TX = 6ul,  USART1_TX = 4ul, }; 
    };

    struct PG12 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 12u;
      enum { ETH1_PHY_INTN = 11ul,  FMC_NE4 = 12ul,  LPTIM1_IN1 = 1ul,  LTDC_B1 = 14ul,  LTDC_B4 = 9ul,  SAI4_CK2 = 6ul,  SAI4_SCK_A = 10ul,  SPDIFRX_IN1 = 8ul,  SPI6_MISO = 5ul,  USART6_DE = 7ul,  USART6_RTS = 7ul, }; 
    };

    struct PG13 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 13u;
      enum { DEBUG_TRACED0 = 0ul,  ETH1_TXD0 = 11ul,  FMC_A24 = 12ul,  LPTIM1_OUT = 1ul,  LTDC_R0 = 14ul,  SAI1_CK2 = 2ul,  SAI1_SCK_A = 6ul,  SAI4_CK1 = 4ul,  SAI4_MCLK_A = 10ul,  SPI6_SCK = 5ul,  USART6_CTS = 7ul,  USART6_NSS = 7ul, }; 
    };

    struct PG14 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 14u;
      enum { DEBUG_TRACED1 = 0ul,  ETH1_TXD1 = 11ul,  FMC_A25 = 12ul,  LPTIM1_ETR = 1ul,  LTDC_B0 = 14ul,  QUADSPI_BK2_IO3 = 9ul,  SAI4_D1 = 6ul,  SAI4_SD_A = 10ul,  SPI6_MOSI = 5ul,  USART6_TX = 7ul, }; 
    };

    struct PG15 
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 15u;
      enum { DCMI_D13 = 13ul,  DEBUG_TRACED7 = 0ul,  I2C2_SDA = 4ul,  SAI1_D2 = 2ul,  SAI1_FS_A = 6ul,  SDMMC3_CK = 10ul,  USART6_CTS = 7ul,  USART6_NSS = 7ul, }; 
    };

    struct PG2  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 2u;
      enum { DEBUG_TRACED2 = 0ul,  ETH1_TXD6 = 11ul,  FMC_A12 = 12ul,  RCC_MCO_2 = 1ul,  TIM8_BKIN = 3ul, }; 
    };

    struct PG3  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 3u;
      enum { DEBUG_TRACED3 = 0ul,  DFSDM1_CKIN1 = 4ul,  ETH1_TXD7 = 11ul,  FMC_A13 = 12ul,  TIM8_BKIN2 = 3ul, }; 
    };

    struct PG4  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 4u;
      enum { ETH1_GTX_CLK = 11ul,  FMC_A14 = 12ul,  TIM1_BKIN2 = 1ul, }; 
    };

    struct PG5  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 5u;
      enum { ETH1_CLK125 = 11ul,  FMC_A15 = 12ul,  TIM1_ETR = 1ul, }; 
    };

    struct PG6  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D12 = 13ul,  DEBUG_TRACED14 = 0ul,  LTDC_R7 = 14ul,  SDMMC2_CMD = 10ul,  TIM17_BKIN = 1ul, }; 
    };

    struct PG7  
    {
      constexpr static Port kPort = Port::G;
    constexpr static std::uint32_t kPin = 7u;
        enum { DCMI_D13 = 13ul,  DEBUG_TRACED5 = 0ul,  LTDC_CLK = 14ul,  QUADSPI_BK2_IO3 = 11ul,  QUADSPI_CLK = 9ul,  SAI1_MCLK_A = 6ul,  UART8_DE = 8ul,  UART8_RTS = 8ul,  USART6_CK = 7ul, }; 
    };

    struct PG8  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 8u;
      enum { DEBUG_TRACED15 = 0ul,  ETH1_CLK = 2ul,  ETH1_PPS_OUT = 11ul,  LTDC_G7 = 14ul,  SAI4_D2 = 6ul,  SAI4_FS_A = 10ul,  SPDIFRX_IN2 = 9ul,  SPI6_NSS = 5ul,  TIM2_CH1 = 1ul,  TIM2_ETR = 1ul,  TIM8_ETR = 3ul,  USART3_DE = 8ul,  USART3_RTS = 8ul,  USART6_DE = 7ul,  USART6_RTS = 7ul, }; 
    };

    struct PG9  
    {
      constexpr static Port kPort = Port::G;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_VSYNC = 13ul,  DEBUG_DBTRGO = 0ul,  FMC_NCE = 12ul,  FMC_NE2 = 12ul,  LTDC_R1 = 14ul,  QUADSPI_BK2_IO2 = 9ul,  SAI2_FS_B = 10ul,  SPDIFRX_IN3 = 8ul,  USART6_RX = 7ul, }; 
    };

    struct PH0  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 0u;
      enum {}; 
    };

    struct PH1  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 1u;
      enum {}; 
    };

    struct PH10 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 10u;
      enum { DCMI_D1 = 13ul,  I2C1_SMBA = 5ul,  I2C4_SMBA = 4ul,  LTDC_R4 = 14ul,  TIM5_CH1 = 2ul, }; 
    };

    struct PH11 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 11u;
      enum { DCMI_D2 = 13ul,  I2C1_SCL = 5ul,  I2C4_SCL = 4ul,  LTDC_R5 = 14ul,  TIM5_CH2 = 2ul, }; 
    };

    struct PH12 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 12u;
      enum { DCMI_D3 = 13ul,  HDP_HDP2 = 0ul,  I2C1_SDA = 5ul,  I2C4_SDA = 4ul,  LTDC_R6 = 14ul,  TIM5_CH3 = 2ul, }; 
    };

    struct PH13 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 13u;
      enum { FDCAN1_TX = 9ul,  LTDC_G2 = 14ul,  TIM8_CH1N = 3ul,  UART4_TX = 8ul, }; 
    };

    struct PH14 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 14u;
      enum { DCMI_D4 = 13ul,  FDCAN1_RX = 9ul,  LTDC_G3 = 14ul,  TIM8_CH2N = 3ul,  UART4_RX = 8ul, }; 
    };

    struct PH15 
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 15u;
      enum { DCMI_D11 = 13ul,  LTDC_G4 = 14ul,  TIM8_CH3N = 3ul, }; 
    };

    struct PH2  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 2u;
      enum { ETH1_CRS = 11ul,  LPTIM1_IN2 = 1ul,  LTDC_R0 = 14ul,  QUADSPI_BK2_IO0 = 9ul,  SAI2_SCK_B = 10ul, }; 
    };

    struct PH3  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 3u;
      enum { DFSDM1_CKIN4 = 3ul,  ETH1_COL = 11ul,  LTDC_R1 = 14ul,  QUADSPI_BK2_IO1 = 9ul,  SAI2_MCLK_B = 10ul, }; 
    };

    struct PH4  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 4u;
      enum { I2C2_SCL = 4ul,  LTDC_G4 = 14ul,  LTDC_G5 = 9ul, }; 
    };

    struct PH5  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2C2_SDA = 4ul,  SAI4_SD_B = 12ul,  SPI5_NSS = 5ul, }; 
    };

    struct PH6  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D8 = 13ul,  ETH1_RXD2 = 11ul,  I2C2_SMBA = 4ul,  MDIOS_MDIO = 12ul,  SPI5_SCK = 5ul,  TIM12_CH1 = 2ul, }; 
    };

    struct PH7  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 7u;
      enum { DCMI_D9 = 13ul,  ETH1_RXD3 = 11ul,  I2C3_SCL = 4ul,  MDIOS_MDC = 12ul,  SPI5_MISO = 5ul, }; 
    };

    struct PH8  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 8u;
      enum { DCMI_HSYNC = 13ul,  I2C3_SDA = 4ul,  LTDC_R2 = 14ul,  TIM5_ETR = 2ul, }; 
    };

    struct PH9  
    {
      constexpr static Port kPort = Port::H;
      constexpr static std::uint32_t kPin = 9u;
      enum { DCMI_D0 = 13ul,  I2C3_SMBA = 4ul,  LTDC_R3 = 14ul,  TIM12_CH2 = 2ul, }; 
    };

    struct PI0  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 0u;
      enum { DCMI_D13 = 13ul,  I2S2_WS = 5ul,  LTDC_G5 = 14ul,  SPI2_NSS = 5ul,  TIM5_CH4 = 2ul, }; 
    };

    struct PI1  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 1u;
      enum { DCMI_D8 = 13ul,  I2S2_CK = 5ul,  LTDC_G6 = 14ul,  SPI2_SCK = 5ul,  TIM8_BKIN2 = 3ul, }; 
    };

    struct PI10 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 10u;
      enum { ETH1_RX_ER = 11ul,  HDP_HDP0 = 0ul,  LTDC_HSYNC = 14ul,  USART3_CTS = 8ul,  USART3_NSS = 8ul, }; 
    };

    struct PI11 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 11u;
      enum { I2S_CKIN = 5ul,  LTDC_G6 = 9ul,  RCC_MCO_1 = 0ul, }; 
    };

    struct PI12 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 12u;
      enum { DEBUG_TRACED0 = 0ul,  HDP_HDP0 = 2ul,  LTDC_HSYNC = 14ul, }; 
    };

    struct PI13 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 13u;
      enum { DEBUG_TRACED1 = 0ul,  HDP_HDP1 = 2ul,  LTDC_VSYNC = 14ul, }; 
    };

    struct PI14 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 14u;
      enum { DEBUG_TRACECLK = 0ul,  LTDC_CLK = 14ul, }; 
    };

    struct PI15 
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 15u;
      enum { LTDC_G2 = 9ul,  LTDC_R0 = 14ul, }; 
    };

    struct PI2  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 2u;
      enum { DCMI_D9 = 13ul,  I2S2_SDI = 5ul,  LTDC_G7 = 14ul,  SPI2_MISO = 5ul,  TIM8_CH4 = 3ul, }; 
    };

    struct PI3  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 3u;
      enum { DCMI_D10 = 13ul,  I2S2_SDO = 5ul,  SPI2_MOSI = 5ul,  TIM8_ETR = 3ul, }; 
    };

    struct PI4  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 4u;
      enum { DCMI_D5 = 13ul,  LTDC_B4 = 14ul,  SAI2_MCLK_A = 10ul,  TIM8_BKIN = 3ul, }; 
    };

    struct PI5  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 5u;
      enum { DCMI_VSYNC = 13ul,  LTDC_B5 = 14ul,  SAI2_SCK_A = 10ul,  TIM8_CH1 = 3ul, }; 
    };

    struct PI6  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 6u;
      enum { DCMI_D6 = 13ul,  LTDC_B6 = 14ul,  SAI2_SD_A = 10ul,  TIM8_CH2 = 3ul, }; 
    };

    struct PI7  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 7u;
      enum { DCMI_D7 = 13ul,  LTDC_B7 = 14ul,  SAI2_FS_A = 10ul,  TIM8_CH3 = 3ul, }; 
    };

    struct PI8  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 8u;
      enum {}; 
    };

    struct PI9  
    {
      constexpr static Port kPort = Port::I;
      constexpr static std::uint32_t kPin = 9u;
      enum { FDCAN1_RX = 9ul,  HDP_HDP1 = 0ul,  LTDC_VSYNC = 14ul,  UART4_RX = 8ul, }; 
    };

    struct PJ0  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 0u;
      enum { DEBUG_TRACED8 = 0ul,  LTDC_R1 = 14ul,  LTDC_R7 = 9ul, }; 
    };

    struct PJ1  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 1u;
      enum { DEBUG_TRACED9 = 0ul,  LTDC_R2 = 14ul, }; 
    };

    struct PJ10 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 10u;
      enum { LTDC_G3 = 14ul,  SPI5_MOSI = 5ul,  TIM1_CH2N = 1ul,  TIM8_CH2 = 3ul, }; 
    };

    struct PJ11 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 11u;
      enum { LTDC_G4 = 14ul,  SPI5_MISO = 5ul,  TIM1_CH2 = 1ul,  TIM8_CH2N = 3ul, }; 
    };

    struct PJ12 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 12u;
      enum { LTDC_B0 = 14ul,  LTDC_G3 = 9ul, }; 
    };

    struct PJ13 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 13u;
      enum { LTDC_B1 = 14ul,  LTDC_G4 = 9ul, }; 
    };

    struct PJ14 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 14u;
      enum { LTDC_B2 = 14ul, }; 
    };

    struct PJ15 
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 15u;
      enum { LTDC_B3 = 14ul, }; 
    };

    struct PJ2  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 2u;
      enum { DEBUG_TRACED10 = 0ul,  DSIHOST_TE = 13ul,  LTDC_R3 = 14ul, }; 
    };

    struct PJ3  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 3u;
      enum { DEBUG_TRACED11 = 0ul,  LTDC_R4 = 14ul, }; 
    };

    struct PJ4  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 4u;
      enum { DEBUG_TRACED12 = 0ul,  LTDC_R5 = 14ul, }; 
    };

    struct PJ5  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 5u;
      enum { DEBUG_TRACED2 = 0ul,  HDP_HDP2 = 2ul,  LTDC_R6 = 14ul, }; 
    };

    struct PJ6  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 6u;
      enum { DEBUG_TRACED3 = 0ul,  HDP_HDP3 = 2ul,  LTDC_R7 = 14ul,  TIM8_CH2 = 3ul, }; 
    };

    struct PJ7  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 7u;
      enum { DEBUG_TRACED13 = 0ul,  LTDC_G0 = 14ul,  TIM8_CH2N = 3ul, }; 
    };

    struct PJ8  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 8u;
      enum { DEBUG_TRACED14 = 0ul,  LTDC_G1 = 14ul,  TIM1_CH3N = 1ul,  TIM8_CH1 = 3ul,  UART8_TX = 8ul, }; 
    };

    struct PJ9  
    {
      constexpr static Port kPort = Port::J;
      constexpr static std::uint32_t kPin = 9u;
      enum { DEBUG_TRACED15 = 0ul,  LTDC_G2 = 14ul,  TIM1_CH3 = 1ul,  TIM8_CH1N = 3ul,  UART8_RX = 8ul, }; 
    };

    struct PK0  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 0u;
      enum { LTDC_G5 = 14ul,  SPI5_SCK = 5ul,  TIM1_CH1N = 1ul,  TIM8_CH3 = 3ul, }; 
    };

    struct PK1  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 1u;
      enum { DEBUG_TRACED4 = 0ul,  HDP_HDP4 = 2ul,  LTDC_G6 = 14ul,  SPI5_NSS = 5ul,  TIM1_CH1 = 1ul,  TIM8_CH3N = 3ul, }; 
    };

    struct PK2  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 2u;
      enum { DEBUG_TRACED5 = 0ul,  HDP_HDP5 = 2ul,  LTDC_G7 = 14ul,  TIM1_BKIN = 1ul,  TIM8_BKIN = 3ul, }; 
    };

    struct PK3  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 3u;
      enum { LTDC_B4 = 14ul, }; 
    };

    struct PK4  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 4u;
      enum { LTDC_B5 = 14ul, }; 
    };

    struct PK5  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 5u;
      enum { DEBUG_TRACED6 = 0ul,  HDP_HDP6 = 2ul,  LTDC_B6 = 14ul, }; 
    };

    struct PK6  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 6u;
      enum { DEBUG_TRACED7 = 0ul,  HDP_HDP7 = 2ul,  LTDC_B7 = 14ul, }; 
    };

    struct PK7  
    {
      constexpr static Port kPort = Port::K;
      constexpr static std::uint32_t kPin = 7u;
      enum { LTDC_DE = 14ul, }; 
    };

    struct PZ0  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 0u;
      enum { I2C2_SCL = 3ul,  I2C6_SCL = 2ul,  I2S1_CK = 5ul,  SPI1_SCK = 5ul,  SPI6_SCK = 8ul,  USART1_CK = 7ul, }; 
    };

    struct PZ1  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 1u;
      enum { I2C2_SDA = 3ul,  I2C4_SDA = 6ul,  I2C5_SDA = 4ul,  I2C6_SDA = 2ul,  I2S1_SDI = 5ul,  SPI1_MISO = 5ul,  SPI6_MISO = 8ul,  USART1_RX = 7ul, }; 
    };

    struct PZ2  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 2u;
      enum { I2C2_SCL = 3ul,  I2C4_SMBA = 6ul,  I2C5_SMBA = 4ul,  I2C6_SCL = 2ul,  I2S1_SDO = 5ul,  SPI1_MOSI = 5ul,  SPI6_MOSI = 8ul,  USART1_TX = 7ul, }; 
    };

    struct PZ3  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 3u;
      enum { I2C2_SDA = 3ul,  I2C4_SDA = 6ul,  I2C5_SDA = 4ul,  I2C6_SDA = 2ul,  I2S1_WS = 5ul,  SPI1_NSS = 5ul,  SPI6_NSS = 8ul,  USART1_CTS = 7ul,  USART1_NSS = 7ul, }; 
    };

    struct PZ4  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 4u;
      enum { I2C2_SCL = 3ul,  I2C4_SCL = 6ul,  I2C5_SCL = 4ul,  I2C6_SCL = 2ul, }; 
    };

    struct PZ5  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 5u;
      enum { I2C2_SDA = 3ul,  I2C4_SDA = 6ul,  I2C5_SDA = 4ul,  I2C6_SDA = 2ul,  USART1_DE = 7ul,  USART1_RTS = 7ul, }; 
    };

    struct PZ6  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 6u;
      enum { I2C2_SCL = 3ul,  I2C4_SMBA = 6ul,  I2C6_SCL = 2ul,  I2S1_MCK = 5ul,  USART1_CK = 4ul,  USART1_RX = 7ul, }; 
    };

    struct PZ7  
    {
      constexpr static Port kPort = Port::Z;
      constexpr static std::uint32_t kPin = 7u;
      enum { I2C2_SDA = 3ul,  I2C6_SDA = 2ul,  USART1_TX = 7ul, }; 
    };
    
  } // inline namespace 
} // namespace mpp::io 
 
